runtime: python27
api_version: 1
threadsafe: true

skip_files:
- node_modules/
- .eslintrc.js
- .gitignore
- package.json
- package-lock.json

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always